In [68]:
#Create and train a classifier on top of the mediapipe hand landmarker.
#Its input will be the hand landmark and its output will be the label of the gesture done by the user.
#It will be done using the keras framework

#needs tensorflow, pandas, numpy and sklearn


import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from sklearn.model_selection import train_test_split

# Load the CSV file into a DataFrame
data = pd.read_csv('D:\progetto_video\dataset\dataset_nuovo_sx.csv')

#Otherwise, online download:
'''
import requests

url = "https://github.com/leviens/Live-human-gesture-recognition-system/blob/main/dataset/dataset_nuovo_sx.csv"
response = requests.get(url)

with open("dataset_nuovo_sx.csv", "wb") as f:
    f.write(response.content)

print("File downloaded successfully.")
'''


# The last colums is the label, the rest are the variables
features = data.iloc[:, :-1].values
labels = data.iloc[:, -1].values
labels[:]-=1

# One-hot encode the labels 
labels = tf.keras.utils.to_categorical(labels)
#print(labels)


# Normalize the features 
features = features.astype('float32')

#Normalization: we apply a simple normalization as other types didn't work as well on this dataset
features = features / np.max(features)

features, X_test, labels, y_test = train_test_split(features, labels, test_size=0.2, random_state=42)

# Define the model
model = Sequential([
    Dense(256, activation='relu', input_shape=(features.shape[1],)), # Input layer with size matching the number of features
    Dropout(0.5), #dropout layer
    Dense(128, activation='relu'), # Hidden layer
    Dropout(0.5), #dropout layer
    Dense(labels.shape[1], activation='softmax')  # Output layer with size matching the number of classes
])

# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
model.fit(features, labels, epochs=200, batch_size=32, validation_split=0.2)

# Optionally, evaluate the model on a test dataset (not provided here)
# test_loss, test_accuracy = model.evaluate(test_features, test_labels)
# print(f'Test accuracy: {test_accuracy:.4f}')


<>:10: SyntaxWarning: invalid escape sequence '\p'
<>:10: SyntaxWarning: invalid escape sequence '\p'
C:\Users\Marco\AppData\Local\Temp\ipykernel_10128\3258306183.py:10: SyntaxWarning: invalid escape sequence '\p'
  data = pd.read_csv('D:\progetto_video\dataset\dataset_nuovo_sx.csv')


[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
Epoch 1/200


C:\Users\Marco\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


315/315 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.3105 - loss: 1.6399 - val_accuracy: 0.7484 - val_loss: 0.9593
Epoch 2/200
315/315 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6538 - loss: 0.9395 - val_accuracy: 0.8172 - val_loss: 0.5213
Epoch 3/200
315/315 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7704 - loss: 0.6295 - val_accuracy: 0.8899 - val_loss: 0.3729
Epoch 4/200
315/315 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8280 - loss: 0.4852 - val_accuracy: 0.8963 - val_loss: 0.3376
Epoch 5/200
315/315 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8607 - loss: 0.4174 - val_accuracy: 0.9340 - val_loss: 0.2362
Epoch 6/200
315/315 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8845 - loss: 0.3492 - val_accuracy: 0.9412 - val_loss: 0.2168
Epoch 7/200
315/315 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8942 - loss: 0.3267 - val_accuracy: 0.9404 - val_loss: 0.2032
Epoch 8/200
315/315 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9047 - loss: 0.2981 - val_accuracy: 0.9507

In [69]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f'Test accuracy: {test_accuracy:.4f}')

99/99 ━━━━━━━━━━━━━━━━━━━━ 0s 673us/step - accuracy: 0.9798 - loss: 0.0733
Test accuracy: 0.9787


In [70]:
#saves the model remotely

import os
model.save(os.path.join('D:\progetto_video\model','my_model_sx.h5'))


<>:2: SyntaxWarning: invalid escape sequence '\p'
<>:2: SyntaxWarning: invalid escape sequence '\p'
C:\Users\Marco\AppData\Local\Temp\ipykernel_10128\3892193602.py:2: SyntaxWarning: invalid escape sequence '\p'
  model.save(os.path.join('D:\progetto_video\model','my_model_sx.h5'))


In [71]:
model.summary()

Model: "sequential_12"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_36 (Dense)                     │ (None, 256)                 │          16,640 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_24 (Dropout)                 │ (None, 256)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_37 (Dense)                     │ (None, 128)                 │          32,896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_25 (Dropout)                 │ (None, 128)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_38 (Dense)                     │ (None, 6)                   │             774 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 150,932 (589.58 KB)

 Trainable params: 50,310 (196.52 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 100,622 (393.06 KB)

In [72]:
#more in depth analysis of the results on the test set
y_pred = model.predict(X_test)  

#Convert one-hot encoded predictions to label indices
y_pred_labels = np.argmax(y_pred, axis=1)

#Convert one-hot encoded y_test to label indices
y_test_labels = np.argmax(y_test, axis=1)

from sklearn.metrics import classification_report

print(classification_report(y_test_labels, y_pred_labels))

99/99 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step  
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       445
           1       0.93      0.98      0.96       426
           2       0.98      0.95      0.97       566
           3       0.97      0.99      0.98       594
           4       0.99      0.98      0.99       513
           5       1.00      0.97      0.98       601

    accuracy                           0.98      3145
   macro avg       0.98      0.98      0.98      3145
weighted avg       0.98      0.98      0.98      3145

